### ISSUE TITLE
Naming kernel from "current folder name" is messy

### ISSUE THREAD

**Issue by aecorn** [statisticsnorway/ssb-project-cli#253]
This leads to kernels named "notebooks" etc.
Taking the name from the current pyproject.toml would be cleaner.
![image](https://github.com/statisticsnorway/ssb-project-cli/assets/20161657/ea9cb2c7-7aea-4b91-a89d-45326c0f50a3)

**Comment by Jonathan7SSB** [comment]
I have seen this issue a couple of times with other users. I'm surprised that it doesnt search for the root so that the kernel gets the correct name.

**Comment by mmwinther** [comment]
@aecorn @Jonathan7SSB I agree this is incorrect behaviour, we should be using the package name for this. I'll take a look at this.
