### ISSUE TITLE
Artikelnummer aus Angebot kopieren und auf der Website einfügen funktioniert nicht

### ISSUE THREAD

**Issue by MarkusMonschein** [statisticsnorway/ssb-project-cli#30]
Wenn eine Artikelnummer aus dem Angebot kopiert und in die Suchlupe der HP eingefügt wird, wird der Artikel NICHT gefunden.

Siehe:
Suchergebnis, wenn die Artikelnummer aus dem Angebot kopiert wird:
![image](https://user-images.githubusercontent.com/114983505/193774150-1425e77d-2bc1-4a34-be87-a35dd4ef8284.png)

Suchergebnis, wenn die Artikelnummer händisch eingegeben wird:
![image](https://user-images.githubusercontent.com/114983505/193774294-c0a7c9c3-26e9-4f9e-bff8-b1d6c310f91b.png)

**Comment by mmwinther** [comment]
@MarkusMonschein you're in the wrong place.
