### ISSUE TITLE
ssb-project build does not respect python-location in "in-project venv"

### ISSUE THREAD

**Issue by aecorn** [statisticsnorway/ssb-project-cli#333]
Using `ssb-project build` replaces path to the python version to a central location:
![image](https://github.com/statisticsnorway/ssb-project-cli/assets/20161657/08b49c35-0071-412f-9600-81d8a95d5080)
While the location is actually inside the project under .venv/bin/python3
This breaks the kernel's connection to the venv.

**Comment by mmwinther** [comment]
This should be fixed in v1.3.1
