### ISSUE TITLE
ssb-project-cli fungerer ikke i prod-sonen

### ISSUE THREAD

**Issue by benediktgoodman** [statisticsnorway/ssb-project-cli#460]
Kort sagt så ser det ut som poetry ikke får til å installere pakker. Det ser ut til at den får en ConnectionError når den prøver å installere selve virtual environmentet. Mulig at proxyen til CLIet ikke fungere som den skal?

Her er feilmeldingen man får i terminalen:
![bilde](https://github.com/user-attachments/assets/5961cee5-2c09-4a9d-84fc-bf2dfe6220d4)

Her er detaljerte loggfiler:
[poetry-install-error-1727689821.txt](https://github.com/user-attachments/files/17187834/poetry-install-error-1727689821.txt)
[ssb-project-debug.log](https://github.com/user-attachments/files/17187912/ssb-project-debug.log)

**Comment by arneso-ssb** [comment]
@benediktgoodman Jeg ser av loggen at det kommer en http 104 feil: Connection reset by peer. Den kommer på OS-nivå, så det er neppe noe feil på selve ssb-project-cli. Sannsynligvis noe på nettverk eller proxy-nivå.

Jeg testet og det virker igjen nå.
![image](https://github.com/user-attachments/assets/af238c54-aa00-4fae-b621-49db98ff1565)

Lukker saken.
